# Generated by Django 5.2 on 2025-10-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'financeiro_banco',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], default='D', max_length=1, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('boleto', 'Boleto'), ('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Documento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('conta_corrente', models.CharField(max_length=100, verbose_name='Conta Corrente')),
                ('cancelado', models.BooleanField(verbose_name='Cancelado')),
                ('tipo', models.BooleanField(default=True, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data de Emissão')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_compensacao', models.DateField(blank=True, null=True, verbose_name='Data de Compensação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pago', models.BooleanField(default=False)),
                ('hospede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hospede', verbose_name='Hóspede')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Título Financeiro',
                'verbose_name_plural': 'Títulos Financeiros',
                'db_table': 'financeiro_titulo',
            },
        ),
    ]
