# Generated by Django 5.2 on 2025-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='tipo',
            field=models.BooleanField(default=True, verbose_name='Tipo'),
        ),
    ]
