# Generated by Django 5.2 on 2025-10-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_seed_bancos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('tipo', 'descricao')},
        ),
    ]
