# Generated by Django 5.2 on 2025-09-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_titulo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
