# Generated by Django 5.2 on 2025-10-15 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='financeiro.categoria', verbose_name='Categoria'),
        ),
    ]
