# Generated by Django 5.2 on 2025-11-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificacao'),
        ('financeiro', '0004_titulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='core.reserva', verbose_name='Reserva'),
        ),
    ]
