# Generated by Django 5.2 on 2025-09-24 13:05

from django.db import migrations

def seed_bancos(apps, schema_editor):
    Banco = apps.get_model("financeiro", "Banco")
    bancos = [
        ("001", "Banco do Brasil S.A."),
        ("341", "Itaú Unibanco S.A."),
        ("260", "Nu Pagamentos S.A. (Nubank)"),
        ("336", "C6 Bank S.A."),
        ("104", "Caixa Econômica Federal"),
        ("208", "Banco BTG Pactual S.A."),
        ("077", "Banco Inter S.A."),
    ]
    for codigo, descricao in bancos:
        Banco.objects.update_or_create(
            codigo=str(codigo), defaults={"descricao": descricao}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_banco'),
    ]

    operations = [
        migrations.RunPython(seed_bancos),
    ]
