# Generated by Django 5.2 on 2025-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_titulo_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulo',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Título Financeiro', 'verbose_name_plural': 'Títulos Financeiros'},
        ),
        migrations.AlterField(
            model_name='titulo',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
