# Generated by Django 5.2 on 2025-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço'),
        ),
    ]
