# Generated by Django 5.2 on 2025-06-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_financeiro', models.IntegerField(verbose_name='ID Financeiro')),
                ('id_hospede', models.IntegerField(verbose_name='ID Hóspede')),
                ('id_quarto', models.IntegerField(verbose_name='ID Quarto')),
                ('data_check_in', models.DateField(verbose_name='Check-in')),
                ('data_check_out', models.DateField(verbose_name='Check-out')),
                ('data_reserva', models.DateField(verbose_name='Data da Reserva')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
            ],
        ),
    ]
