# Generated by Django 5.2 on 2025-10-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'db_table': 'hospede',
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('descricao', models.TextField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
            ],
            options={
                'db_table': 'quarto',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_check_in', models.DateTimeField(blank=True, null=True, verbose_name='Check-in')),
                ('data_check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check-out')),
                ('data_reserva_inicio', models.DateField(blank=True, null=True, verbose_name='Data início da Reserva')),
                ('data_reserva_fim', models.DateField(blank=True, null=True, verbose_name='Data fim da Reserva')),
                ('quantidade_dias', models.IntegerField(default=0, verbose_name='Quantidade de Dias')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('status', models.CharField(choices=[('PREVISTA', 'Prevista'), ('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PREVISTA', max_length=10, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('id_hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospede', verbose_name='Hóspede')),
                ('id_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quarto', verbose_name='Quarto')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
