# Generated by Django 5.2 on 2025-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='tipo_quarto',
            field=models.CharField(choices=[('SUITE', 'Quarto Suite'), ('TERREO', 'Chalé Térreo'), ('LOFT', 'Chalé Loft'), ('FLAT', 'flat')], default='SUITE', max_length=15, verbose_name='Tipo de Quarto'),
        ),
        migrations.AlterModelTable(
            name='quarto',
            table=None,
        ),
    ]
