# Generated by Django 5.2 on 2025-06-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quantidade_dias',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Dias'),
        ),
    ]
