# Generated by Django 5.2 on 2025-06-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva_quantidade_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_hospede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospede', verbose_name='Hóspede'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quarto', verbose_name='Quarto'),
        ),
    ]
