# Generated by Django 5.2 on 2025-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quarto_tipo_quarto_alter_quarto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quantidade_pessoas',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de Pessoas'),
        ),
    ]
