# Generated by Django 5.2 on 2025-10-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reserva_quantidade_pessoas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='quantidade_pessoas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_adultos',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de Adultos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_crianças',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de Crianças'),
        ),
    ]
