# Generated by Django 5.2 on 2025-06-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reserva_id_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_reserva_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim da Reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_reserva_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data início da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_check_out',
            field=models.DateField(blank=True, null=True, verbose_name='Check-out'),
        ),
    ]
