# Generated by Django 5.2 on 2025-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reserva_quantidade_pessoas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='quantidade_crianças',
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_criancas',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Crianças'),
        ),
    ]
