# Generated by Django 5.2 on 2025-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reserva_data_reserva_reserva_data_reserva_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-out'),
        ),
    ]
