# Generated by Django 5.2 on 2025-10-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reserva_quantidade_crianças_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo_quarto',
            field=models.CharField(choices=[('SUITE', 'Quarto Suite'), ('TERREO', 'Chalé Térreo'), ('LOFT', 'Chalé Loft'), ('FLAT', 'Flat')], default='SUITE', max_length=15, verbose_name='Tipo de Quarto'),
        ),
    ]
