# Generated by Django 5.2 on 2025-10-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hospede_cpf_alter_quarto_tipo_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
