# Generated by Django 5.2 on 2025-09-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reserva_data_check_in_and_more'),
    ]

    operations = [
    ]
