# Generated by Django 5.2 on 2025-10-24 11:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hospede_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal Acordado')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Vencimento')),
                ('data_inicio', models.DateField(verbose_name='Data de Início do Contrato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Contrato Ativo?')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('hospede', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.hospede', verbose_name='Hóspede')),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quarto', verbose_name='Quarto Fixo')),
            ],
            options={
                'verbose_name': 'Mensalista',
                'verbose_name_plural': 'Mensalistas',
            },
        ),
    ]
