# Generated by Django 5.2 on 2025-09-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250907_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PREVISTA', 'Prevista'), ('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PREVISTA', max_length=10),
        ),
    ]
