# Generated by Django 5.2 on 2025-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_hospede_cep_alter_hospede_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
