# Generated by Django 5.2 on 2025-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_hospede_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='passaporte',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Passaporte'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
