# Generated by Django 5.2 on 2025-09-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reserva_status'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE reserva ALTER COLUMN status SET DEFAULT 'PREVISTA';
                UPDATE reserva SET status = 'PREVISTA' WHERE status IS NULL;
            """,
            reverse_sql="""
                ALTER TABLE reserva ALTER COLUMN status DROP DEFAULT;
            """,
        ),
    ]
