# Generated by Django 5.2 on 2025-11-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hospede_passaporte_alter_hospede_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.CharField(max_length=5),
        ),
    ]
