# Generated by Django 5.2 on 2025-10-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ajuste_status_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospede',
            options={'verbose_name': 'Hóspede', 'verbose_name_plural': 'Hóspedes'},
        ),
        migrations.AddField(
            model_name='hospede',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
