# Generated by Django 5.2 on 2025-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ajuste_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email_confirmacao_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
