# Generated by Django 5.2 on 2025-11-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_quarto_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
