# Generated by Django 5.2 on 2025-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_quarto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PREVISTA', 'Prevista'), ('CONFIRMADA', 'Confirmada'), ('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PREVISTA', max_length=10, null=True),
        ),
    ]
