# Generated by Django 5.2 on 2025-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='capacidade',
            field=models.PositiveSmallIntegerField(default=2, help_text='Número máximo de pessoas que o quarto acomoda.', verbose_name='Capacidade'),
            preserve_default=False,
        ),
    ]
