# Generated by Django 5.2 on 2025-11-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hospede_cpf'),
        ('core', '0014_alter_reserva_status'),
    ]

    operations = [
    ]
