# Generated by Django 5.2 on 2025-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_quarto_capacidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADO', 'Ocupado'), ('MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=15, verbose_name='Status'),
        ),
    ]
