# Generated by Django 5.2 on 2025-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='passaporte',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Passaporte'),
        ),
    ]
